# Generated by Django 4.1.5 on 2023-01-24 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record_names",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("counter_id", models.IntegerField()),
                ("record_name", models.CharField(max_length=50)),
                ("is_calculated_diff", models.BooleanField()),
                ("record_names_rus", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Records",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("counter_id", models.IntegerField()),
                ("date_record", models.DateField()),
                ("record", models.FloatField()),
                ("record_diff", models.FloatField()),
                ("period", models.IntegerField()),
                (
                    "record_name_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="first_task.record_names",
                    ),
                ),
            ],
        ),
    ]
